version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_DATABASE: nlw_proffy
      MYSQL_ROOT_PASSWORD: pswd123
    ports:
      - 3306:3306
    networks:
      - mysql_network
    volumes:
      - mysql_volume:/var/lib/mysql

networks:
  mysql_network:
    driver: bridge

volumes:
  mysql_volume:
    driver: local
